
version: "3.8"

services: 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  #declare a service to RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
    - 5672:5672 #first used by the service
    - 15672:15672 #second to call rabbitMq port
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes: 
  mongodbdata:
  rabbitmqdata:
